name: Update DSA Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Get DSA Stats SVG
        run: |
          curl https://dsastats.vercel.app/api?username=Sayan0361 > dsa-stats.svg
      - name: Commit & Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dsa-stats.svg
          git commit -m "Update DSA Stats"
          git push
