name: Update DSA Stats

on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight UTC
  workflow_dispatch: # Manual trigger

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout main branch
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      # Step 2: Download the latest DSA stats image
      - name: Fetch DSA Stats SVG
        run: curl -o dsa-stats.svg "https://dsastats.vercel.app/api?username=Sayan_Sen"

      # Step 3: Commit and push changes to main
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add dsa-stats.svg
          git commit -m "Update DSA Stats" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
